### PR TITLE
Use strict match

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by xpepermint** [comment]
@fulldecent  What you did is the right way and I use `===` all the time, but there's an exception. In frontend applications data are in most cases received as strings and you'll have to cast all values received from e.g. a form to numbers. I can tell you that this is a pretty common case and frontend devs are not used to do this kind of conversions. I would leave `==` if that's ok?

**Comment by fulldecent** [comment]
Got it, for checking enums we will use == because in the compiled JS it will be compatible with `String` class.

There are some remaining items in the PR which can still switch to ===.

**Comment by xpepermint** [comment]
Good, please make changes and I'll merge.

**Comment by fulldecent** [comment]
Updated and reduced any check of enums.

Probably some of those checks I just removed could use === but it was too hard for me to trace which will be based on JavaScript user input.

**Comment by xpepermint** [comment]
@fulldecent please make sure tests are passing

**Pull request merged**
