### PR TITLE
Add eth_sendRawTransaction method to use the privateKey of the user account

### PR DESCRIPTION
**Pull request by sebaponti**
This is my implementation to use the ethereum method `eth_sendRawTransactions` to sign transactions using the privateKey of the user account. It works for our needs and I know it's not the best solution but the idea can help you and others to implement this new feature.

Regards!.

### CODE REVIEW

**Comment by xpepermint** [comment]
Thank you @sebaponti. We will look at this soon.

**Comment by sebaponti** [comment]
Any update about this functionality?

**Comment by xpepermint** [comment]
Sorry for waiting, @sebaponti. Still looking for alternatives at the moment.

**Comment by maxidev** [comment]
> Sorry for waiting, @sebaponti. Still looking for alternatives at the moment.

Hi @xpepermint sorry to bother you. This pull request was needed and modified by us (www.cryptologic.io) to use it and sign raw transactions. It's tested and it's working, can we maybe work together to make it better so you can accept the pull request?
Regards,
Max.

**Comment by xpepermint** [comment]
@sebaponti we are in the process of refactoring the framework to `v2.0` and unfortunately, this issue is not currently a priority. Please bear with us and maintain this branch for your internal purpose until we decide how to incorporate this feature into the core. Thanks!

**Comment by fulldecent** [comment]
Only regarding v1 product. I think this PR is good to merge but only after a test case is added.

**Comment by xpepermint** [comment]
@maxidev as @fulldecent wrote, we can merge this PR into `v1` but we need tests for your PR. The `v2` framework follows a different strategy thus it won't have this feature included. Please let me know what you think.

**Comment by xpepermint** [comment]
@maxidev feel free to reopen this issue.

**Comment by xpepermint** [comment]
@sebaponti @maxidev raw transactions are supported by passing your custom client to the generic provider where you override the `send` method.

**Pull request closed without merging**
